-- Create Table
CREATE TABLE [SPOTIFY].[dbo].[DIM_ALBUM]
(
ALBUM_SID int IDENTITY (0, 1),
ALBUM_SPOTIFY_ID varchar(50),
ALBUM_NAME varchar(100),
ARTIST_SID int,
ARTIST_SPOTIFY_ID varchar(50),
ARTIST_NAME varchar(100),
RELEASE_DATE_SID int,
RELEASE_DATE datetime,
TOTAL_TRACKS int,
PRIMARY KEY (ALBUM_SID),
FOREIGN KEY (ARTIST_SID) REFERENCES DIM_ARTIST(ARTIST_SID)
)
;

-- Insert Dummy Row
INSERT INTO [SPOTIFY].[dbo].[DIM_ALBUM] VALUES ('', 'Unknown Album', 0, '', 'Unknown Artist', 19000101, '1900-01-01', 0)