--Create Table
CREATE TABLE [SPOTIFY].[dbo].[FACT_PLAYS]
(
TRACK_SID int,
TRACK_SPOTIFY_ID varchar(50),
ARTIST_SID int,
ARTIST_SPOTIFY_ID varchar(50),
ALBUM_SID int,
ALBUM_SPOTIFY_ID varchar(50),
PLAYED_DATETIME datetime,
PLAYED_DATE_SID int,
PLAYED_DATE datetime
FOREIGN KEY (TRACK_SID)  REFERENCES DIM_TRACK(TRACK_SID),
FOREIGN KEY (ARTIST_SID) REFERENCES DIM_ARTIST(ARTIST_SID),
FOREIGN KEY (ALBUM_SID)  REFERENCES DIM_ALBUM(ALBUM_SID)
)